Repository bespoyasov/refactor-like-a-superhero, pull requests merged in 2022-10, with the labels that each got.

#5 Fix controversial sentence about changing names
  manuscript-en/06-names.md
  manuscript-en/23-sources.md
  manuscript-ru/06-names.md
  manuscript-ru/23-sources.md
Labels: typo or phrasing, enhancement

#10 Update 09-functional-pipeline.md
  manuscript-en/09-functional-pipeline.md
  manuscript-en/TOC.md
  manuscript-ru/09-functional-pipeline.md
  manuscript-ru/TOC.md
Labels: enhancement

#12 Fix typo in "Error Handling" chapter (RU)
  manuscript-ru/12-error-handling.md
Labels: typo or phrasing

#13 Adjust error message in "Error Handling" (RU, EN)
  manuscript-en/12-error-handling.md
  manuscript-ru/12-error-handling.md
Labels: typo or phrasing

#19 Update 12-error-handling.md
  manuscript-ru/12-error-handling.md
Labels: typo or phrasing

#20 Update 15-architecture.md
  manuscript-ru/15-architecture.md
Labels: typo or phrasing

#21 Update 23-sources.md
  manuscript-ru/23-sources.md
Labels: typo or phrasing

#22 Fix typo in "Test Code" chapter (RU)
  manuscript-ru/18-test-code.md
Labels: typo or phrasing

#23 Make commit word consistent across chapters (RU)
  manuscript-ru/06-names.md
  manuscript-ru/18-test-code.md
  manuscript-ru/19-comments-and-docs.md
  manuscript-ru/20-refactoring-process.md
  manuscript-ru/21-afterword.md
  manuscript-ru/22-cheatsheet.md
Labels: typo or phrasing, enhancement

#24 Update 18-test-code.md
  manuscript-ru/18-test-code.md
Labels: typo or phrasing
