Repository bespoyasov/refactor-like-a-superhero, pull requests merged in 2022-11, with the labels that each got.

#34 fix typo
  manuscript-ru/11-side-effects.md
Labels: typo or phrasing

#35 fix(13-module-integration.md): rename the variable to calc total
  manuscript-en/13-module-integration.md
  manuscript-ru/13-module-integration.md
Labels: typo or phrasing, example

#37 fix typo "всешл" -> "всего"
  manuscript-ru/12-error-handling.md
Labels: typo or phrasing

#39 Update 11-side-effects.md
  manuscript-ru/11-side-effects.md
Labels: typo or phrasing

#40 fix typo `код код`
  manuscript-ru/12-error-handling.md
Labels: typo or phrasing

#41 fix typo `Ели`
  manuscript-ru/12-error-handling.md
Labels: typo or phrasing

#42 Update 13-module-integration.md
  manuscript-ru/13-module-integration.md
Labels: typo or phrasing

#43 fix typo
  manuscript-ru/15-architecture.md
Labels: typo or phrasing

#44 Fix typo
  manuscript-ru/16-declarative-style.md
  manuscript-ru/17-static-typing.md
Labels: typo or phrasing, example

#45 Update function parameter
  manuscript-ru/08-abstraction.md
Labels: example

#47 Adds missing argument to the code snippet in Chapter 8
  manuscript-en/08-abstraction.md
  manuscript-ru/08-abstraction.md
Labels: error, example
