Repository bespoyasov/refactor-like-a-superhero, pull requests merged in 2023-02, with the labels that each got.

#51 Use data preparation instead of serialization term
  manuscript-en/08-abstraction.md
  manuscript-ru/08-abstraction.md
Labels: enhancement, discussion, error

#58 Clarify the usage of “changes” in the immutability section
  manuscript-en/11-side-effects.md
  manuscript-ru/11-side-effects.md
Labels: enhancement

#56 Fix parseUser and meaning of throwing error sentence
  manuscript-en/12-error-handling.md
  manuscript-ru/12-error-handling.md
Labels: typo or phrasing

#59 Сlarification about never in signature
  manuscript-en/12-error-handling.md
  manuscript-ru/12-error-handling.md
Labels: enhancement

#62 Fix typos
  manuscript-ru/16-declarative-style.md
  manuscript-ru/17-static-typing.md
  manuscript-ru/18-test-code.md
Labels: typo or phrasing
